INSERT INTO bandss.discharge (category,part_name,operation_method,viscosity,specific_gravity,discharge_accuracy,median_discharge_amount,keywords,control,etc,primeCost,supply,userKRW,userUSD,AUTOMATION,CURING_CONDITIONS,FILLER_SUPPORT,HOW_TO_USE_IT,ONE_COMPONENT_OR_TWO,SUPPLY_FORM,USE_TWO_COMPONENT_CARTRIDGE,SUPPROT_PASTE) VALUES
	 ('BARREL','BARREL','공압',NULL,NULL,20,NULL,'Barrel에 액체를 넣어 직접 토출|
공압으로 제어','Tad-200s','Barrel Bracket',100,'BR-05|BR-10|BR-30|BR-50|BR-05-UV|BR-10-UV|BR-30-UV|BR-50-UV',1000,NULL,'EVERYTHING','EVERYTHING','EVERYTHING','EVERYTHING','ONE_COMPONENT','BARREL_SYRINGE','NO','NO'),
	 ('Cartridge','Single Cartridge','공압',NULL,NULL,20,NULL,'Cartridge에 담긴 액체를 직접 토출
공압으로 제어','Tad-200s','Cartridge Bracket',200000,'1K CR',400000,NULL,'EVERYTHING','EVERYTHING','EVERYTHING','EVERYTHING','ONE_COMPONENT','CARTRIDGE','NO','NO'),
	 ('직접 토출','BX-2','진공 TUBE',300,2,5,0.2,'진공으로 액체 이송|
체적 계량식|
높은 정량성',NULL,NULL,219745,NULL,1200000,660,'MANUAL','EVERYTHING','NO','EVERYTHING','ONE_COMPONENT','EVERYTHING','NO','NO'),
	 ('직접 토출','MMA','MOTOR',NULL,NULL,1,250.0,'Servo Motor 제어|
다양한 카트리지에 대응|
1%의 정량성',NULL,NULL,2500000,NULL,6000000,NULL,'Automated','EVERYTHING','EVERYTHING','EVERYTHING','EVERYTHING','CARTRIDGE','YES','EVERYTHING'),
	 ('직접 토출','BS-1','MOTOR',NULL,2,1,0.2085,'Servo Motor 제어|
실험실 Syringe에 대응|
1%의 정량성|
저점도 액상 대응',NULL,NULL,2500000,NULL,4500000,NULL,'EVERYTHING','EVERYTHING','NO','EVERYTHING','ONE_COMPONENT','BARREL_SYRINGE','NO','NO'),
	 ('일반 VALVE','BV-302','Needle OFF Valve',NULL,2,10,66.5,'빠른 반응 속도','Tad-200v ','Valve Bracket',83330,NULL,500000,NULL,'EVERYTHING','EVERYTHING','EVERYTHING','EVERYTHING','ONE_COMPONENT','EVERYTHING','NO','NO'),
	 ('일반 VALVE','BV-303','Suck Back Valve',NULL,2,10,66.5,'빠른 반응 속도','Tad-200v ','Valve Bracket',95870,NULL,500000,NULL,'EVERYTHING','EVERYTHING','EVERYTHING','EVERYTHING','ONE_COMPONENT','EVERYTHING','NO','NO'),
	 ('일반 VALVE','BV-325','Suck Back Valve',NULL,2,10,233.0,'빠른 반응 속도','Tad-200v ','Valve Bracket',105930,NULL,550000,NULL,'EVERYTHING','EVERYTHING','EVERYTHING','EVERYTHING','ONE_COMPONENT','EVERYTHING','NO','NO'),
	 ('일반 VALVE','BV-386','Needle OFF Valve',NULL,NULL,10,66.5,'고점도 액상에 대응|
빠른 반응 속도','Tad-200v ','Valve Bracket',143629,NULL,580000,NULL,'EVERYTHING','EVERYTHING','EVERYTHING','EVERYTHING','ONE_COMPONENT','EVERYTHING','NO','EVERYTHING'),
	 ('일반 VALVE','BV-396','Suck Back Valve',NULL,NULL,10,333.0,'고점도 액상에 대응|
빠른 반응 속도','Tad-200v ','Valve Bracket',200000,NULL,750000,NULL,'EVERYTHING','EVERYTHING','EVERYTHING','EVERYTHING','ONE_COMPONENT','EVERYTHING','NO','EVERYTHING');
INSERT INTO bandss.discharge (category,part_name,operation_method,viscosity,specific_gravity,discharge_accuracy,median_discharge_amount,keywords,control,etc,primeCost,supply,userKRW,userUSD,AUTOMATION,CURING_CONDITIONS,FILLER_SUPPORT,HOW_TO_USE_IT,ONE_COMPONENT_OR_TWO,SUPPLY_FORM,USE_TWO_COMPONENT_CARTRIDGE,SUPPROT_PASTE) VALUES
	 ('일반 VALVE','BV-3893','Needle OFF Valve',NULL,NULL,10,233.0,'고점도 액상에 대응|
빠른 반응 속도|
대용량 토출 대응','Tad-200v ','Valve Bracket',167783,NULL,800000,NULL,'EVERYTHING','EVERYTHING','EVERYTHING','EVERYTHING','ONE_COMPONENT','EVERYTHING','NO','EVERYTHING'),
	 ('일반 VALVE','BV-3892','Needle OFF Valve',NULL,NULL,10,333.0,'고점도 액상에 대응|
빠른 반응 속도|
대용량 토출 대응','Tad-200v ','Valve Bracket',204743,NULL,900000,NULL,'EVERYTHING','EVERYTHING','EVERYTHING','EVERYTHING','ONE_COMPONENT','EVERYTHING','NO','EVERYTHING'),
	 ('일반 VALVE','BV-520P','Needle OFF Valve',NULL,2,5,6.5,'정밀한 양 조절|
정밀노즐 사용','Tad-200s','Valve Bracket',170000,NULL,800000,NULL,'EVERYTHING','EVERYTHING','EVERYTHING','EVERYTHING','ONE_COMPONENT','EVERYTHING','NO','NO'),
	 ('일반 VALVE','BV-520M','Needle OFF Valve',NULL,2,5,6.5,'정밀한 양 조절','Tad-200s','Valve Bracket',150000,NULL,750000,NULL,'EVERYTHING','EVERYTHING','EVERYTHING','EVERYTHING','ONE_COMPONENT','EVERYTHING','NO','NO'),
	 ('일반 VALVE','BV-520PK','Needle OFF Valve',NULL,2,5,6.5,'정밀한 양 조절|
혐기성 액상에 대응','Tad-200s','Valve Bracket',250000,NULL,900000,NULL,'EVERYTHING','ANAEROBIC_REACTION','EVERYTHING','EVERYTHING','ONE_COMPONENT','EVERYTHING','NO','NO'),
	 ('일반 VALVE','BV-300N','Diaphragm Valve',NULL,2,10,2.5,'혐기성 액상에 대응','Tad-200s','Valve Bracket',112094,NULL,500000,NULL,'EVERYTHING','ANAEROBIC_REACTION','NO','EVERYTHING','ONE_COMPONENT','EVERYTHING','NO','NO'),
	 ('일반 VALVE','BV-300T','Diaphragm Valve',NULL,2,10,2.5,'혐기성 액상에 대응','Tad-200s','Valve Bracket',124800,NULL,NULL,NULL,'EVERYTHING','ANAEROBIC_REACTION','NO','EVERYTHING','ONE_COMPONENT','EVERYTHING','NO','NO'),
	 ('Spray Valve','BV-500','SPRAYING',NULL,2,10,66.5,'Conformal Coating 용','Tad-500SR','Valve Bracket',95920,NULL,500000,NULL,'EVERYTHING','EVERYTHING','NO','CONFORMAL_COATING_SPRAYING_SPRAY_VALVE','ONE_COMPONENT','EVERYTHING','NO','NO'),
	 ('Spray Valve','BV-500T','SPRAYING',NULL,2,5,66.5,'Conformal Coating 용|
비산이 적음','Tad-500SR','Valve Bracket',219480,NULL,1000000,NULL,'EVERYTHING','EVERYTHING','NO','CONFORMAL_COATING_SPRAYING_SPRAY_VALVE','ONE_COMPONENT','EVERYTHING','NO','NO'),
	 ('Spray Valve','BV-500P','SPRAYING',NULL,2,1,41.5,'Conformal Coating 용|
비산이 없음','Tad-500SR','Valve Bracket',280000,NULL,1300000,NULL,'EVERYTHING','EVERYTHING','NO','CONFORMAL_COATING_SPRAYING_SPRAY_VALVE','ONE_COMPONENT','EVERYTHING','NO','NO');
INSERT INTO bandss.discharge (category,part_name,operation_method,viscosity,specific_gravity,discharge_accuracy,median_discharge_amount,keywords,control,etc,primeCost,supply,userKRW,userUSD,AUTOMATION,CURING_CONDITIONS,FILLER_SUPPORT,HOW_TO_USE_IT,ONE_COMPONENT_OR_TWO,SUPPLY_FORM,USE_TWO_COMPONENT_CARTRIDGE,SUPPROT_PASTE) VALUES
	 ('Actuator Valve','BV-600C','ACTUATOR VALVE',NULL,NULL,5,66.5,'고점도 액상에 대응|
Actuator 방식|
LIne 시작과 끝에 뭉침이 없음','Tad-200v ','Valve Bracket',568336,NULL,1600000,NULL,'EVERYTHING','EVERYTHING','EVERYTHING','EVERYTHING','ONE_COMPONENT','EVERYTHING','NO','NO'),
	 ('2액형 VALVE','BV-T900','Suck Back Valve',NULL,NULL,10,466.5,'고점도 액상에 대응|
2액형','Tad-200v ','Valve Bracket',294780,NULL,1200000,NULL,'EVERYTHING','EVERYTHING','EVERYTHING','EVERYTHING','TWO_COMPONENT','EVERYTHING','NO','EVERYTHING'),
	 ('2액형 VALVE','BV-T900-MINI','Suck Back Valve',NULL,NULL,10,133.0,'고점도 액상에 대응|
2액형|
Compact한 사이즈
','Tad-200v ','Valve Bracket',230000,NULL,900000,NULL,'EVERYTHING','EVERYTHING','EVERYTHING','EVERYTHING','TWO_COMPONENT','EVERYTHING','NO','EVERYTHING'),
	 ('PC PUMP','SPP-050','ROTOR&STATOR',NULL,2,1,0.0505,'Endless piston 방식|
1%의 정량성','BP-2','Valve Bracket',190000,NULL,800000,NULL,'Automated','EVERYTHING','NO','EVERYTHING','ONE_COMPONENT','EVERYTHING','NO','NO'),
	 ('PC PUMP','SPP-500','ROTOR&STATOR',NULL,2,1,0.505,'Endless piston 방식|
1%의 정량성','BP-2','Valve Bracket',2300000,NULL,8000000,NULL,'Automated','EVERYTHING','NO','EVERYTHING','ONE_COMPONENT','EVERYTHING','NO','NO'),
	 ('PC PUMP','SPP-100','ROTOR&STATOR',NULL,2,1,0.101,'Endless piston 방식|
1%의 정량|
2액형','BP-2','Valve Bracket',2300000,NULL,8000000,NULL,'Automated','EVERYTHING','NO','EVERYTHING','TWO_COMPONENT','EVERYTHING','NO','NO'),
	 ('PC PUMP','SPP-1000','ROTOR&STATOR',NULL,2,1,1.01,'Endless piston 방식|
1%의 정량성|
2액형','BP-2','Valve Bracket',5500000,NULL,16000000,NULL,'Automated','EVERYTHING','NO','EVERYTHING','TWO_COMPONENT','EVERYTHING','NO','NO'),
	 ('METERING VALVE','BV-M06','METERING VALVE',NULL,NULL,1,3.0,'고점도 액상에 대응|
체적 계량식|
Shot 당 6cc','Tad-200v ','Valve Bracket',5500000,NULL,16000000,NULL,'EVERYTHING','EVERYTHING','EVERYTHING','EVERYTHING','ONE_COMPONENT','EVERYTHING','NO','EVERYTHING'),
	 ('METERING VALVE','BV-0250T','METERING VALVE',NULL,2,1,0.0125,'체적 계량식|
Shot 당 0.25cc','Tad-200v ','Valve Bracket',206090,NULL,800000,NULL,'EVERYTHING','EVERYTHING','EVERYTHING','EVERYTHING','ONE_COMPONENT','EVERYTHING','NO','NO');
